package com.sma.backend.dao;

import net.sf.mardao.core.CursorPage;

import com.sma.backend.domain.DCategory;

/**
 * Business Methods interface for entity DCategory.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-01-23T22:14:35.572+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DCategoryDao extends GeneratedDCategoryDao {

	// TODO: declare your Business Methods here
    CursorPage<DCategory> queryPageWithSortField(int pageSize, String cursorString,
            int sortBy, boolean isAscending);
}
